### ISSUE TITLE
Issue with bone.GetVars()

### ISSUE THREAD

**Issue by lindemannrichard** [go-zoo/bone#16]
Just a quick thought.

Example: 
```go
runtime.GOMAXPROCS(2)
mux.Get("/home/:id", Handler)
````

And as http.ListenAndServe() emits each client in the separate goroutine, 
it might happen that two clients access /home/1 and /home/2 at the same time. 

According to the variant of the GetValue()  as a global var , it I'm not sure that both clients will get the correct bone.GetValue("id").

**Comment by squiidz** [comment]
yeah, i was not sure of this change too :/ i'm still testing it.

**Comment by squiidz** [comment]
you were right, thanks for the advice !

**Comment by bakins** [comment]
Also, nothing cleans up var, so it will possibly grow without bounds.  Also, access to it needs to be protected by a Mutex. See how how gorilla did it in https://github.com/gorilla/context/blob/master/context.go

This will "slow" it down, which is why some routers use a 3rd parameter.

**Comment by squiidz** [comment]
the vars stack is clean up every request at line 58 of bone.go.

**Comment by bakins** [comment]
so two concurrent requests and vars may disappear for one of them depending on timing?

**Comment by bakins** [comment]
Now I see it - but none of those accesses are protected by a mutex it seems
