### ISSUE TITLE
Query string not working in nested routers

### ISSUE THREAD

**Issue by sporto** [go-zoo/bone#23]
I have a sub route like:

```
subRouter.GetFunc("*/users", ...)
mainRouter.Get("/app/*", subRouter)
```

This matches `/app/users`, but I can't figure out how to match the same path with an added query string. e.g. `/app/users?active=true` or `/app/users?foo=1&bar=3`

I just get 404s. When I use a query string in the main router it works, but somehow a sub router fails. Any clues?

**Comment by squiidz** [comment]
i will look at this, probably tomorrow ! And thanks for the report.

**Comment by squiidz** [comment]
it's seems to work for now, just check the unstable branch. It's not final, but it should do the work until i found a better way to do it !

**Comment by squiidz** [comment]
Done, it's should work now !
