### ISSUE TITLE
Subrouter path issue

### ISSUE THREAD

**Issue by aniketawati** [go-zoo/bone#25]
```
     mux := bone.New()

	sub := bone.New()

	sub.GetFunc("/test/example", func(rw http.ResponseWriter, req *http.Request) {
		rw.Write([]byte("From Sub router !"))
	})

	mux.Get("/api", sub)
```
This is example from Readme, and it doesn't work. But example 003 in examples folder, works. Only difference is the path of the subrouter. If subrouter has more than 1 hardcoded pathsegments, it doesn't work. Example - `"/test/example"` Doesn't work.  Whereas  this - `"/user/:id" ` works.

**Comment by squiidz** [comment]
I just update the subroutine,  just try the last version :)

**Comment by aniketawati** [comment]
Yes, the last version works. But I want the static route to also work. Like this -
```
        muxx := bone.New()
        sub := bone.New()
        sub.GetFunc("/user/test", func(rw http.ResponseWriter, req *http.Request) {
                rw.Write([]byte("test this"))
                return
        })
        muxx.Get("/api", sub)

        http.ListenAndServe(":8080", muxx)
```

This gives 404 right now.

**Comment by squiidz** [comment]
... sorry i did the update, but forget to push it -_-

**Comment by aniketawati** [comment]
:+1: Fixed. Thanks!

**Comment by squiidz** [comment]
No problem :)
