### ISSUE TITLE
Panic running example 001

### ISSUE THREAD

**Issue by husio** [go-zoo/bone#26]
I got panic running example code:

```
% go run 001/example.go -race

2015/10/03 20:58:39 http: panic serving [::1]:45814: runtime error: invalid memory address or nil pointer dereference
goroutine 182 [running]:
net/http.(*conn).serve.func1(0xc8201786e0, 0x7f33df087650, 0xc820080398)
        /usr/lib/go/src/net/http/server.go:1287 +0xb5
github.com/go-zoo/bone.(*Route).Match(0xc8200b0c80, 0xc820171880, 0xc820083a00)
        /tmp/b/src/github.com/go-zoo/bone/route.go:101 +0x28f
github.com/go-zoo/bone.(*Mux).parse(0xc820076cf0, 0x7f33df0877d0, 0xc820178790, 0xc820171880, 0x0)
        /tmp/b/src/github.com/go-zoo/bone/helper.go:29 +0x31d
github.com/go-zoo/bone.(*Mux).ServeHTTP(0xc820076cf0, 0x7f33df0877d0, 0xc820178790, 0xc820171880)
        /tmp/b/src/github.com/go-zoo/bone/bone.go:49 +0x43
net/http.serverHandler.ServeHTTP(0xc8200700c0, 0x7f33df0877d0, 0xc820178790, 0xc820171880)
        /usr/lib/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8201786e0)
        /usr/lib/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:1910 +0x3f6
```

tested with curl:
```
% (repeat 100 {curl localhost:8080/home/foo & })
```

**Comment by squiidz** [comment]
just test it with the same curl command, and even at 1000 request, i does'nt get any error :/

**Comment by husio** [comment]
If you're using go 1.4, set your GOMAXPROCS to something higher than 1. Then run in one console
```bash
$ go run 001/example.go -race   2>&1 >/dev/null | grep panic
```
and curl:
```bash
(repeat 1000 {curl -s localhost:8080/home/foo > /dev/null & })
```

You're not locking global `vars` dict, so it's failing because of race
condition. You need some luck to reproduce it, but keep trying and it should
show up ;)

**Comment by squiidz** [comment]
It should be ok now ! :)

**Comment by djherbis** [comment]
Did you notice any performance impact when you added the Lock?

**Comment by squiidz** [comment]
not really, maybe something like 3-4 ns/op

**Comment by djherbis** [comment]
I think you might want to try it with some more concurrent tests though, it'll probably be slower if its under contention (multiple requests will want to operate on the lock).

Also I still see some races in there:
https://github.com/go-zoo/bone/blob/9b6ba1a4fe36dc41c7870a21f8197459b857257b/route.go#L104
https://github.com/go-zoo/bone/blob/9b6ba1a4fe36dc41c7870a21f8197459b857257b/route.go#L111
https://github.com/go-zoo/bone/blob/9b6ba1a4fe36dc41c7870a21f8197459b857257b/helper.go#L31
https://github.com/go-zoo/bone/blob/9b6ba1a4fe36dc41c7870a21f8197459b857257b/helper.go#L95
https://github.com/go-zoo/bone/blob/9b6ba1a4fe36dc41c7870a21f8197459b857257b/helper.go#L100

Anytime you are read/writing to that global map you'll need a lock.

**Comment by squiidz** [comment]
ok, thanks for the advice ! I will look at this :)

**Comment by djherbis** [comment]
No problem, if you need a hand or want a pull-request just let me know.

**Comment by squiidz** [comment]
If you want to resolve the issue with the race condition, I would be really grateful for your contribution!
