### ISSUE TITLE
Add support for fasthttp

### ISSUE THREAD

**Issue by valyala** [go-zoo/bone#35]
[fasthttp](https://github.com/valyala/fasthttp) provides http server optimized for speed. It would be great if bone will support fasthttp alongside net/http.

**Comment by squiidz** [comment]
Would be great,  if you want to send me a pull request, I could add it to bone. But I will take the a look.

**Comment by coderhaoxin** [comment]
Maybe I can send a PR a few days later!

**Comment by squiidz** [comment]
great ! :+1:
