### ISSUE TITLE
Problem in setting Route.Atts bitflag

### ISSUE THREAD

**Issue by eelcovb** [go-zoo/bone#49]
In route.go the (Route *)save method seems to have a problem in the way the r.Atts variable is set; += operators are used in stead of |= operators. This will cause an issue when for example there are 4 parameters set in the routing path. Using r.Atts +=PARAM will eventually set r.Atts flagged with the WC bit set therefore ignoring the rest of the request when matched against that particular routing path.

Please let me know if you want to receive a PR.

**Comment by squiidz** [comment]
Hi, if you're able to make a PR, it would be really appreciated! :)
