### ISSUE TITLE
Go 1.7 context package

### ISSUE THREAD

**Issue by dimiro1** [go-zoo/bone#50]
Do have any plan to update the package to use the new [context](https://tip.golang.org/pkg/context/) package from the go 1.7?

https://tip.golang.org/pkg/net/http/#Request.Context

**Comment by squiidz** [comment]
probably, i just have to look if the performance doesn't drop.

**Comment by skabbes** [comment]
I have a PR that implements this here: https://github.com/go-zoo/bone/pull/54
