### ISSUE TITLE
Concurrency issue in route.go

### ISSUE THREAD

**Issue by eelcovb** [go-zoo/bone#51]
Hi,
There is a concurrency issue in route.go:104

at:
                        for k, v := range r.Pattern {
                                vars.v[req][v] = ss[k]
                        }

vars should have a mutex lock enabled before getting ss[k].
I'll see if I have time to create a pull request.

- Eelco

**Comment by skabbes** [comment]
If you just look a few lines above, it actually holds the lock the entire time it is accessing those variables already.  I believe the code you have here will deadlock.

At any rate, I have proposed some changes [here](https://github.com/go-zoo/bone/pull/54) which holds the lock for even less time on <go1.7 and doesn't need to use locks at all on go1.7.
