### ISSUE TITLE
go1.7: using http.Request.WithContext breaks bone GetValues

### ISSUE THREAD

**Issue by skabbes** [go-zoo/bone#53]
If you use the go1.7 contexts in the http lifecycle sometime after bone has routed your request, but before the application specific routes are run, then bone is unable to find the values from the request.

There are a few workarounds, but given how common it will be for new go users to build this pattern, I think it would be helpful to enable this use case without too many "WTF's".  The changes are fairly simple I think - probably require storing the bone values in the request's context, and I am happy to help make this change.  I just wanted to get the OK from a project maintainer before proceeding to code anything.

```go
func (r AuthedRoute) ServeHTTP(w http.ResponseWriter, req *http.Request) {
    user := r.AuthedUser()
    ctx := context.WithValue(req.Context(), authKey, user)
    
    // adding this line this breaks bone values, since it uses the *http.Request as the key 
    req = req.WithContext(ctx)
    needsBoneHandler(w, req)
}

func needsBoneHandler(w http.ResponseWriter, req *http.Request) {
    boneVals := bone.GetAllValues(req)
    // is empty :(
}
```

**Comment by squiidz** [comment]
Hi, thanks for the feedback, if you want to implement your solution, I'm more than ok with that :)

**Comment by skabbes** [comment]
Great, I put up a PR here https://github.com/go-zoo/bone/pull/54
