### ISSUE TITLE
case insensitive urls

### ISSUE THREAD

**Issue by jaybeecave** [go-zoo/bone#55]
Is there any support for using case insensitive urls?

Say I have a page at `http://test.com/promo/` and the user types `http://test.com/Promo/` I would like it to still match.

Sorry if there is a feature I am missing that allows for this.

**Comment by squiidz** [comment]
No currently routes are case sensitive ... I will take a look to add this feature.

**Comment by squiidz** [comment]
I added a flag `CaseSentative` on `Mux` which is true by default, but it should enable you to set it too insensitive by setting it to `false` ! :)

**Comment by jaybeecave** [comment]
Brilliant Man!

**Comment by squiidz** [comment]
No problem i will fix this, english is my second language ... Sorry for the typo

**Comment by jaybeecave** [comment]
No need to be sorry, English is my first language and I still had to google it :)
