### ISSUE TITLE
Cookies dont have domain and path info

### ISSUE THREAD

**Issue by jaybeecave** [go-zoo/bone#56]
When I was using Gorrila Mux a cookie would get the correct path and domain information when I used `http.SetCookie(w, cookie)`

Swapping to bone I get 

![image](https://cloud.githubusercontent.com/assets/1089671/20645913/22e364f8-b4d2-11e6-9751-a18e2b64ac57.png)

Let me know if you need more info

**Comment by squiidz** [comment]
Weird ... I will look at this, thanks for the info

**Comment by jaybeecave** [comment]
I am not setting path and domain when I create the cookie fyi

```
func (padlock *Padlock) LoginReturningCookie(email string, password string, tableName string) (*http.Cookie, error) {
	tokenName := getSessionUserCookieName()

	token, err := padlock.LoginReturningToken(email, password, tableName) // same process / different format
	if err != nil {
		return nil, err
	}
	cookie := &http.Cookie{Name: tokenName, Value: token.Token, Expires: token.Expiration}
	return cookie, nil
}
```
