### ISSUE TITLE
Method is not set on individual routes

### ISSUE THREAD

**Issue by KevinSjoberg** [go-zoo/bone#57]
I have a mux with some defined handlers. I want to print out all defined routes as follows:

    POST /endpoint1
    PUT  /endpoint2
    GET  /endpoint3

If I iterate over `mux.Routes` all defined `Route`s have their method set to `""`. I'd expect the field `Method` to be set when the route was defined using `PostFunc`, `GetFunc` and so on.

Am I missing something? How can I programatically check what verb is associated with what route?

Cheers!

**Comment by squiidz** [comment]
Hi, sorry for that, routes methods was used by a other lib that I make last year, which is no longer maintained. So if you want to use this "API" I can patch it, i will take a look at this weekend, thanks !

**Comment by KevinSjoberg** [comment]
@squiidz alrighty, awesome. You want to pair program on or are you almost finished? 😃
