### ISSUE TITLE
getRequestRoute for subroutes

### ISSUE THREAD

**Issue by KevinSjoberg** [go-zoo/bone#62]
Using `getRequestRoute` for sub routes isn't working properly. Let's assume I have the following setup:

```go
func Main() {
    mux := bone.New()
    mux.SubRoute("/v0", apiMux)
    http.ListenAndServe("127.0.0.1:3000", mux)
}
```

`apiMux` have the following endpoints registered:

```go
apiMux.Post("/users", usersHandler)
apiMux.Post("/posts", postsHandler)
```

Doing a request to `/users` will generate a `http.Request` with an URL equal to `/v0/users`. Calling `getRequestRoute(req)` returns `/v0`. I'd assume it returns `/v0/users` or `/users`.

Is this a bug? If so, how do we want to fix it? I'd be happy to help in any way possible.

**Comment by squiidz** [comment]
Hi, yes that's a bug ... I think the getRequestRoute method was implemented before the SubRoute functionality, so it's probably just a minor change to handle sub route in getRequestRoute.

**Comment by squiidz** [comment]
It should be fixed

**Comment by KevinSjoberg** [comment]
Thank you. Appreciate it! 👍
