### ISSUE TITLE
I doubt about the speed of bone than other Mux like httprouter

### ISSUE THREAD

**Issue by nullne** [go-zoo/bone#64]
I roughly read the code, and find that you simply loop all registered routers within a http method to find a match. I doubt this is faster than using a compact prefix tree (or just Radix tree) referenced by httprouter. 

can you explain this ?

**Comment by squiidz** [comment]
On small apps with not a ton a routes a linear search is really fast, bone is not intended for big apps with hundreds of different routes.

**Comment by nullne** [comment]
but number of routes grows. it's better to use Radix tree or something like. 
BTW, I like the project name
