### ISSUE TITLE
Static files browser caching

### ISSUE THREAD

**Issue by jaybeecave** [go-zoo/bone#66]
Just running a site in production through google page speed insights and getting `expiration not specified` errors for static files. Is there a way in bone to specify 

> Setting an expiry date or a maximum age in the HTTP headers for static resources instructs the browser to load previously downloaded resources from local disk rather than over the network.

Code in question is:
```
	r.Mux.Handle("/public/", http.StripPrefix("/public/", http.FileServer(http.Dir("./public/"))))
	r.Mux.Handle("/attachments/", http.StripPrefix("/attachments/", http.FileServer(http.Dir("./attachments/"))))
```
As I write this I am starting to think its not an issue with bone, but I am still unsure of what to do. Any help / point to a feature I should be using would be hugely appreciated.

**Comment by harshvladha** [comment]
```
func staticHandler(w http.ResponseWriter, r *http.Request) {
    w.Header().Set("Cache-Control", "max-age=x")
}
````
You can set header while responding back `Cache-Control: max-age=x`, where *x* is in seconds.


Better option will be to serve static files directly from your load balancer and having header rules at that level.
